export const gqlTableNotFound = `no such table`;
export const gqlNoEditPerms = "cannot edit database";
export const gqlDepNotFound = "no such deployment";
export const gqlNoRefFoundErr = "no such ref in database";
export const gqlPullHasConflicts = "Merge conflict detected";
export const gqlErrorPrimaryKeyChange = "primary key set change";
export const gqlConnectionLost = "Connection lost";
export const gqlDatabaseNotFoundErr = "Database connection not found";
export const gqlDatabasesDoNotMatch = "Databases do not match";
