directories:
  output: dist
  buildResources: build
appId: com.dolthub.dolt-workbench
files:
  - filter:
      - app
      - package.json
extraFiles:
  - filter:
      - graphql-server/dist/*
      - graphql-server/dist/**/*
mac:
  icon: build/icon.icns
  hardenedRuntime: true
  gatekeeperAssess: false
  artifactName: ${productName}-mac-${arch}.${ext}
  target:
    - target: dmg
      arch:
        - x64
        - arm64
linux:
  target:
    - flatpak
    - AppImage
  artifactName: ${productName}-linux.${ext}
flatpak:
  runtimeVersion: '23.08'
  baseVersion: '23.08'
win:
  target:
    - target: appx
      arch:
        - ia32
        - x64
        - arm64
    - target: nsis
      arch:
        - ia32
        - x64
        - arm64
  icon: build/icon.ico
  artifactName: ${productName}-windows-${arch}.${ext}
includeSubNodeModules: false
compression: maximum
asar: true
electronVersion: 31.4.0
