name: Bump build version
description: Bumps SemVer buildVersion in the input builder-config file
inputs:
  platform:
    description: Platform to update builder config yaml file
    required: true
  token:
    description: GitHub token
    required: true
  commit:
    description: If true, will add and commit the new build version. Default false.
    required: false
    default: 'false'
outputs:
  new-version:
    description: The bumped build version
    value: ${{ steps.bump-version.outputs.new_version }}
runs:
  using: "composite"
  steps:
    - name: Get build config file
      id: filepath
      run: |
        echo "build-config-file=web/build/builder-${{ inputs.platform }}-config.yaml" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get current build version
      id: current-build-version
      run: |
        version="$(yq '.buildVersion' ${{ steps.filepath.outputs.build-config-file }})"
        echo "Current buildVersion in ${{ steps.filepath.outputs.build-config-file }} is $version"
        echo "version=$version" >> $GITHUB_OUTPUT
      shell: bash

    - name: Bump version
      uses: "actions-ecosystem/action-bump-semver@v1"
      id: bump-version
      with:
        current_version: ${{ steps.current-build-version.outputs.version }}
        level: patch

    - name: Update ${{ steps.filepath.outputs.build-config-file }} buildVersion
      run: |
        yq -i '.buildVersion = "${{ steps.bump-version.outputs.new_version }}"' ${{ steps.filepath.outputs.build-config-file }}
        echo "New buildVersion in ${{ steps.filepath.outputs.build-config-file }} is ${{ steps.bump-version.outputs.new_version }}"
      shell: bash

    - name: Add and commit new build version
      if: ${{ inputs.commit == 'true' }}
      uses: EndBug/add-and-commit@v9
      with:
        message: "Update ${{ steps.filepath.outputs.build-config-file }} buildVersion to ${{ steps.bump-version.outputs.new_version }} [skip ci]"
        new_branch: release/${{ inputs.platform }}-${{ steps.bump-version.outputs.new_version }}

    - name: Raise PR and merge
      if: ${{ inputs.commit == 'true' }}
      run: |
        gh pr create --base main --head release/${{ inputs.platform }}-${{ steps.bump-version.outputs.new_version }} --title "Update ${{ steps.filepath.outputs.build-config-file }} buildVersion to ${{ steps.bump-version.outputs.new_version }}" --body "Increment version"
        gh pr merge --merge --delete-branch release/${{ inputs.platform }}-${{ steps.bump-version.outputs.new_version }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
