name: Build dolt-workbench for Windows
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: GitHub Release Version Number
        required: true
        type: string

  workflow_call:
    inputs:
      release-version:
        description: Github Release Version Number
        required: true
        type: string
      via-call:
        description: Determines if this workflow was called by another workflow
        required: false
        default: true
        type: boolean

env:
  VIA_CALL: ${{ inputs.via-call || false }}

jobs:
  build-windows:
    name: Build Windows release version
    runs-on: windows-2022
    steps:
      - name: Validate branch
        if: ${{ github.ref_name != 'main' }}
        run: |
          echo "This workflow can only run from 'main' (got '${{ github.ref_name }}')." >&2
          exit 1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          choco install yq -y

      - name: Bump Windows build version
        uses: ./.github/actions/bump-build-version
        with:
          platform: win
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            web/renderer/.next/cache
            web/.next/cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('web/renderer/next.config.js', 'web/package.json', 'web/yarn.lock') }}
          restore-keys: |
            nextjs-${{ runner.os }}-

      - name: Build Windows package
        working-directory: web
        run: |
          yarn build:win
          ls dist

      - name: Upload package to Release ${{ inputs.release-version }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.release-version }}
          files: |
            ${{ github.workspace }}/web/dist/Dolt-Workbench-win-x64.exe

      - name: Upload app store artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ inputs.release-version }}
          path: ${{ github.workspace }}/web/dist/Dolt-Workbench-win-x64.appx
          retention-days: 90
          overwrite: true
          compression-level: 0

  commit-build-version:
    name: Commit new build version
    needs: build-windows
    runs-on: ubuntu-22.04
    concurrency:
      group: commit-build-version
      cancel-in-progress: false
    steps:
      - name: Get branch to checkout
        id: branch-to-update
        run: |
          if [[ ${{ env.VIA_CALL }} == 'true' ]]; then
            echo "branch=release/${{ inputs.release-version }}" >> $GITHUB_OUTPUT
          else
            echo "branch=build/win" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout correct branch
        run: git switch -C ${{ steps.branch-to-update.outputs.branch }}

      - uses: ./.github/actions/bump-build-version
        with:
          platform: win
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: true
