name: Workbench Tests
on:
  pull_request:
    paths:
      - "workbench-cypress/**"
  workflow_dispatch:

env:
  GRAPHQL_PORT: 9002
  WEB_PORT: 3002

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install graphql dependencies
        working-directory: ./graphql-server
        run: |
          yarn

      - name: Install web dependencies
        working-directory: ./web
        run: |
          yarn

      - name: Install cypress dependencies
        working-directory: ./workbench-cypress 
        run: |
          yarn
 
      - name: Run tests
        working-directory: ./workbench-cypress 
        run: |
          # Start servers and store PIDs
          echo "Starting servers..."
          nohup ../graphql-server/yarn dev -- --host 0.0.0.0 --port $GRAPHQL_PORT > ../graphql-server.log 2>&1 &
          GRAPHQL_PID=$!
          nohup ../web/yarn dev -H 0.0.0.0 -p $WEB_PORT > ../web.log 2>&1 &
          WEB_PID=$!

          # Cleanup trap
          trap "kill -9 $GRAPHQL_PID $WEB_PID || true" EXIT

          # Wait for FULL server readiness
          echo "Waiting for servers to be ready..."
          npx wait-on -t 180000 \
            http://localhost:$WEB_PORT \
            http://localhost:$GRAPHQL_PORT \
            tcp:localhost:$GRAPHQL_PORT

          # Add additional stabilization
          sleep 5  # Extra buffer for app initialization
          curl -v http://localhost:$WEB_PORT

          # Run Cypress with CI-specific settings
          yarn cy-run-local --config defaultCommandTimeout=15000,pageLoadTimeout=30000

      - name: Save screenshots of failed tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: |
            cypress/screenshots/**/*.png
            cypress/videos/**/*.mp4
          retention-days: 3
